apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.expose: minio
  creationTimestamp: null
  labels:
    io.kompose.service: s3
  name: s3
  namespace: default
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9001
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: s3
status:
  loadBalancer: {}
