version: "3"
services:
  gameserver-jdk11:
    depends_on:
      cryostat:
        condition: service_healthy
    image: ${GAMESERVER_JDK11_TEST_IMAGE:-quay.io/redhat-java-monitoring/gameserver-cryostat-agent:latest-jdk11}
    hostname: gameserver-jdk11
    ports:
      - "7091"
      - "9494"
      - "25565:25565"
    environment:
      CRYOSTAT_AGENT_APP_NAME: gameserver-jdk11
      CRYOSTAT_AGENT_WEBSERVER_HOST: gameserver-jdk11
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9494
      CRYOSTAT_AGENT_CALLBACK: http://gameserver-jdk11:9494/
      CRYOSTAT_AGENT_BASEURI: ${CRYOSTAT_PROXY_PROTOCOL}://${CRYOSTAT_HTTP_HOST}:${CRYOSTAT_PROXY_PORT}/
      CRYOSTAT_AGENT_BASEURI_RANGE: public
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUST_ALL: "true"
      CRYOSTAT_AGENT_WEBCLIENT_TLS_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_AUTHORIZATION_TYPE: basic
      CRYOSTAT_AGENT_AUTHORIZATION_VALUE: user:pass
      CRYOSTAT_AGENT_API_WRITES_ENABLED: "true"
      CRYOSTAT_AGENT_HARVESTER_TEMPLATE: Profiling
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 300000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"
      VERSION: 1.16.5
      EULA: "true"
      ONLINE_MODE: "false"
      OVERRIDE_SERVER_PROPERTIES: "true"
      ENABLE_JMX: "true"
      JMX_HOST: gameserver-jdk11
      JMX_PORT: "7091"
      JVM_OPTS: -javaagent:/opt/cryostat/agent.jar
