services:
  gameserver:
    # depends_on:
    #   cryostat:
    #     condition: service_healthy
    image: ${GAMESERVER_TEST_IMAGE:-quay.io/redhat-java-monitoring/gameserver-cryostat-agent:latest}
    hostname: gameserver
    ports:
      - "25565"
    environment:
      CRYOSTAT_AGENT_APP_NAME: gameserver
      CRYOSTAT_AGENT_WEBSERVER_HOST: gameserver
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9496
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUSTSTORE_CERT[0]_PATH: /auth_certs/certificate.pem
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUSTSTORE_CERT[0]_TYPE: X.509
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUSTSTORE_CERT[0]_ALIAS: cryostat
      CRYOSTAT_AGENT_CALLBACK: http://gameserver:9496/
      CRYOSTAT_AGENT_BASEURI: ${CRYOSTAT_PROXY_PROTOCOL}://${CRYOSTAT_HTTP_HOST}:${CRYOSTAT_PROXY_PORT}/
      CRYOSTAT_AGENT_BASEURI_RANGE: public
      CRYOSTAT_AGENT_AUTHORIZATION_TYPE: basic
      CRYOSTAT_AGENT_AUTHORIZATION_VALUE: user:pass
      CRYOSTAT_AGENT_API_WRITES_ENABLED: "true"
      CRYOSTAT_AGENT_HARVESTER_TEMPLATE: Profiling
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 300000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"
      MINECRAFT_ONLINE_MODE: "false"
      JAVA_OPTS: >-
        -Dio.cryostat.agent.shaded.org.slf4j.simpleLogger.defaultLogLevel=warn
        -javaagent:/opt/cryostat/agent.jar
    volumes:
      - ${DIR}/compose/auth_certs:/auth_certs:z
    healthcheck:
      test: /usr/bin/healthcheck
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
