services:
  quarkus-cryostat-agent:
    image: ${QUARKUS_TEST_IMAGE:-quay.io/redhat-java-monitoring/quarkus-cryostat-agent:latest}
    # do not add a depends_on:cryostat/depends_on:auth here, so that we can test that the agent is tolerant of that state
    hostname: quarkus-cryostat-agent
    ports:
      - "10010:10010"
    expose:
      - "9977"
    environment:
      JAVA_OPTS_APPEND: >-
        -Djava.util.logging.manager=org.jboss.logmanager.LogManager
        -Dio.cryostat.agent.shaded.org.slf4j.simpleLogger.defaultLogLevel=info
        -javaagent:/deployments/app/cryostat-agent.jar
        -Dcom.sun.management.jmxremote.autodiscovery=false
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=22222
        -Dcom.sun.management.jmxremote.rmi.port=22222
        -Djava.rmi.server.hostname=quarkus-cryostat-agent
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
      QUARKUS_HTTP_HOST: 0.0.0.0
      QUARKUS_HTTP_PORT: 10010
      ORG_ACME_CRYOSTATSERVICE_ENABLED: "false"
      CRYOSTAT_AGENT_APP_NAME: quarkus-cryostat-agent
      CRYOSTAT_AGENT_WEBSERVER_HOST: quarkus-cryostat-agent
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9977
      CRYOSTAT_AGENT_CALLBACK: http://quarkus-cryostat-agent:9977/
      CRYOSTAT_AGENT_BASEURI: ${CRYOSTAT_PROXY_PROTOCOL}://${CRYOSTAT_HTTP_HOST}:${CRYOSTAT_PROXY_PORT}/
      CRYOSTAT_AGENT_BASEURI_RANGE: public
      CRYOSTAT_AGENT_AUTHORIZATION_TYPE: basic
      CRYOSTAT_AGENT_AUTHORIZATION_VALUE: user:pass
      CRYOSTAT_AGENT_HARVESTER_TEMPLATE: Continuous
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 30000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUSTSTORE_CERT[0]_PATH: /auth_certs/certificate.pem
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUSTSTORE_CERT[0]_TYPE: X.509
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUSTSTORE_CERT[0]_ALIAS: cryostat
      CRYOSTAT_AGENT_API_WRITES_ENABLED: "true"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:10010 || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
    volumes:
      - ${DIR}/compose/auth_certs:/auth_certs:z
