version: "3"
services:
  spring-boot-3:
    depends_on:
      cryostat:
        condition: service_healthy
    image: ${SPRING_BOOT_3_TEST_IMAGE:-quay.io/redhat-java-monitoring/spring-boot-3-cryostat-agent:latest}
    hostname: spring-boot-3
    ports:
      - "7001"
      - "9591"
    environment:
      JAVA_OPTS_APPEND: -Dcom.sun.management.jmxremote.port=7001 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -javaagent:/opt/cryostat/cryostat-agent.jar
      CRYOSTAT_AGENT_APP_NAME: spring-boot-3
      CRYOSTAT_AGENT_WEBSERVER_HOST: spring-boot-3
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9591
      CRYOSTAT_AGENT_CALLBACK: http://spring-boot-3:9591/
      CRYOSTAT_AGENT_BASEURI: ${CRYOSTAT_PROXY_PROTOCOL}://${CRYOSTAT_HTTP_HOST}:${CRYOSTAT_PROXY_PORT}/
      CRYOSTAT_AGENT_BASEURI_RANGE: public
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUST_ALL: "true"
      CRYOSTAT_AGENT_WEBCLIENT_TLS_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_AUTHORIZATION_TYPE: basic
      CRYOSTAT_AGENT_AUTHORIZATION_VALUE: user:pass
      CRYOSTAT_AGENT_API_WRITES_ENABLED: "true"
      CRYOSTAT_AGENT_HARVESTER_TEMPLATE: Profiling
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 300000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"
