version: "3"
services:
  wildfly-28:
    depends_on:
      cryostat:
        condition: service_healthy
    image: ${WILDFLY_28_TEST_IMAGE:-quay.io/redhat-java-monitoring/wildfly-28-cryostat-agent:latest}
    hostname: wildfly-28
    ports:
      - "9601"
    environment:
      MODULE_OPTS: -javaagent:/opt/cryostat/cryostat-agent.jar
      CRYOSTAT_AGENT_APP_NAME: wildfly-28
      CRYOSTAT_AGENT_WEBSERVER_HOST: wildfly-28
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9601
      CRYOSTAT_AGENT_CALLBACK: http://wildfly-28:9601/
      CRYOSTAT_AGENT_BASEURI: ${CRYOSTAT_PROXY_PROTOCOL}://${CRYOSTAT_HTTP_HOST}:${CRYOSTAT_PROXY_PORT}/
      CRYOSTAT_AGENT_BASEURI_RANGE: public
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUST_ALL: "true"
      CRYOSTAT_AGENT_WEBCLIENT_TLS_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_AUTHORIZATION_TYPE: basic
      CRYOSTAT_AGENT_AUTHORIZATION_VALUE: user:pass
      CRYOSTAT_AGENT_API_WRITES_ENABLED: "true"
      CRYOSTAT_AGENT_HARVESTER_TEMPLATE: Profiling
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 300000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"

      # when loaded by WildFly MODULE_OPTS, these configurations' default values aren't found
      CRYOSTAT_AGENT_WEBCLIENT_TLS_VERSION: TLSv1.2
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUSTSTORE_TYPE: JKS
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUSTSTORE_PASS_CHARSET: utf-8
      CRYOSTAT_AGENT_WEBCLIENT_CONNECT_TIMEOUT_MS: 1000
      CRYOSTAT_AGENT_WEBCLIENT_RESPONSE_TIMEOUT_MS: 1000
      CRYOSTAT_AGENT_WEBCLIENT_RESPONSE_RETRY_COUNT: 3
      CRYOSTAT_AGENT_WEBSERVER_TLS_VERSION: TLSv1.2
      CRYOSTAT_AGENT_WEBSERVER_TLS_KEYSTORE_PASS: 
      CRYOSTAT_AGENT_WEBSERVER_TLS_KEYSTORE_PASS_CHARSET: utf-8
      CRYOSTAT_AGENT_WEBSERVER_TLS_KEYSTORE_TYPE: PKCS12
      CRYOSTAT_AGENT_WEBSERVER_TLS_CERT_ALIAS: serverCert
      CRYOSTAT_AGENT_WEBSERVER_TLS_CERT_TYPE: X.509
      CRYOSTAT_AGENT_WEBSERVER_CREDENTIALS_USER: user
      CRYOSTAT_AGENT_WEBSERVER_CREDENTIALS_PASS_HASH_FUNCTION: SHA-256
      CRYOSTAT_AGENT_WEBSERVER_CREDENTIALS_PASS_LENGTH: 24

      CRYOSTAT_AGENT_EXIT_SIGNALS: INT,TERM
      CRYOSTAT_AGENT_REGISTRATION_RETRY_MS: 5000
      CRYOSTAT_AGENT_REGISTRATION_CHECK_MS: 60000
      CRYOSTAT_AGENT_REGISTRATION_JMX_IGNORE: "false"
      CRYOSTAT_AGENT_REGISTRATION_JMX_USE_CALLBACK_HOST: "true"
      CRYOSTAT_AGENT_EXIT_DEREGISTRATION_TIMEOUT_MS: 3000

      CRYOSTAT_AGENT_HARVESTER_UPLOAD_TIMEOUT_MS: 30000
      CRYOSTAT_AGENT_HARVESTER_MAX_AGE_MS: 0
      CRYOSTAT_AGENT_HARVESTER_MAX_SIZE_B: 0

      CRYOSTAT_AGENT_SMART_TRIGGER_DEFINITIONS: 
      CRYOSTAT_AGENT_SMART_TRIGGER_EVALUATION_PERIOD_MS: 1000
