services:
  wildfly-23:
    depends_on:
      cryostat:
        condition: service_healthy
    image: ${WILDFLY_23_TEST_IMAGE:-quay.io/redhat-java-monitoring/wildfly-23-cryostat-agent:latest}
    hostname: wildfly-23
    ports:
      - "9600"
    environment:
      MODULE_OPTS: -javaagent:/opt/cryostat/cryostat-agent.jar
      CRYOSTAT_AGENT_APP_NAME: wildfly-23
      CRYOSTAT_AGENT_WEBSERVER_HOST: wildfly-23
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9600
      CRYOSTAT_AGENT_CALLBACK: http://wildfly-23:9600/
      CRYOSTAT_AGENT_BASEURI: ${CRYOSTAT_PROXY_PROTOCOL}://${CRYOSTAT_HTTP_HOST}:${CRYOSTAT_PROXY_PORT}/
      CRYOSTAT_AGENT_BASEURI_RANGE: public
      CRYOSTAT_AGENT_WEBCLIENT_TLS_TRUST_ALL: "true"
      CRYOSTAT_AGENT_WEBCLIENT_TLS_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_AUTHORIZATION_TYPE: basic
      CRYOSTAT_AGENT_AUTHORIZATION_VALUE: user:pass
      CRYOSTAT_AGENT_API_WRITES_ENABLED: "true"
      CRYOSTAT_AGENT_HARVESTER_TEMPLATE: Profiling
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 300000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"
