version: "3"
services:
  auth:
    # the proxy does not actually depend on cryostat being up, but we use this
    # to ensure that when the smoketest tries to open the auth login page in a
    # browser tab, it does so only after the upstream cryostat is actually
    # available to be proxied to
    depends_on:
      cryostat:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32m
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    user: ${UID:-0}
    entrypoint: /bin/sh
    command: -c 'chmod 644 /tmp/oauth2-proxy-alpha-config.yaml && /bin/oauth2-proxy --alpha-config=/tmp/oauth2-proxy-alpha-config.yaml'
    volumes:
      - ./auth-proxy-htpasswd:/tmp/.htpasswd
      - ./oauth2-proxy-alpha-config.yaml:/tmp/oauth2-proxy-alpha-config.yaml
    hostname: auth
    ports:
      - "8080:8080"
    labels:
      kompose.service.expose: "auth"
    environment:
      OAUTH2_PROXY_HTPASSWD_FILE: /tmp/.htpasswd
      OAUTH2_PROXY_HTPASSWD_USER_GROUP: write
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:8080/oauth2/callback
      OAUTH2_PROXY_COOKIE_SECRET: __24_BYTE_COOKIE_SECRET_
    restart: unless-stopped
    healthcheck:
      test: wget -q --spider http://localhost:8080/ping || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
