version: "3"
services:
  cryostat:
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
    image: quay.io/cryostat/cryostat3:dev
    hostname: cryostat3
    expose:
      - "9091"
    ports:
      - "8181:8181"
    labels:
      kompose.service.expose: "cryostat"
    environment:
      CRYOSTAT_JDP_ENABLED: "true"
      JAVA_OPTS_APPEND: "-XX:+FlightRecorder -XX:StartFlightRecording=name=onstart,settings=default,disk=true,maxage=5m -Dcom.sun.management.jmxremote.autodiscovery=true -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9091 -Dcom.sun.management.jmxremote.rmi.port=9091 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8181/health/liveness || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s