version: "3"
services:
  cryostat:
    environment:
      STORAGE_BUCKETS_ARCHIVES_NAME: archivedrecordings
      QUARKUS_S3_ENDPOINT_OVERRIDE: http://s3:4566
      QUARKUS_S3_PATH_STYLE_ACCESS: "true" # needed in smoketest, but if the environment and specific S3 impl supports DNS subdomain style access then that should be preferred
      QUARKUS_S3_AWS_REGION: us-east-1
      QUARKUS_S3_AWS_CREDENTIALS_TYPE: static
      QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_ACCESS_KEY_ID: unused
      QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_SECRET_ACCESS_KEY: unused
  s3:
    image: docker.io/localstack/localstack:1.4.0
    hostname: s3
    ports:
      - "4566:4566"
      - "4577:4577"
    environment:
      SERVICES: s3
      START_WEB: 1
      DEFAULT_REGION: us-east-1
      PORT_WEB_UI: 4577
    volumes:
      - localstack_data:/etc/localstack/init/ready.d:z
      # this buckets.sh hook script isn't working for some reason. In the meantime, after spinning up the localstack instance, do:
      # $ podman exec -it cryostat3_s3_1 /bin/bash
      # $ awslocal s3 mb s3://archivedrecordings
    labels:
      kompose.service.expose: "s3"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:4566 || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes:
  localstack_data:
    driver: local
