version: "3"
services:
  sample-app:
    depends_on:
      cryostat:
        condition: service_healthy
    image: quay.io/andrewazores/vertx-fib-demo:0.12.3
    hostname: vertx-fib-demo-1
    environment:
      HTTP_PORT: 8081
      JMX_PORT: 9093
      CRYOSTAT_AGENT_APP_NAME: "vertx-fib-demo-1"
      CRYOSTAT_AGENT_WEBCLIENT_SSL_TRUST_ALL: "true"
      CRYOSTAT_AGENT_WEBCLIENT_SSL_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_WEBSERVER_HOST: "sample-app"
      CRYOSTAT_AGENT_WEBSERVER_PORT: "8910"
      CRYOSTAT_AGENT_CALLBACK: "http://sample-app:8910/"
      CRYOSTAT_AGENT_BASEURI: "http://cryostat:8181/"
      CRYOSTAT_AGENT_TRUST_ALL: "true"
      CRYOSTAT_AGENT_AUTHORIZATION: "Basic dXNlcjpwYXNz"
    ports:
      - "8081:8081"
    labels:
      io.cryostat.discovery: "true"
      io.cryostat.jmxHost: "sample-app"
      io.cryostat.jmxPort: "9093"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
  quarkus-test-agent:
    image: quay.io/andrewazores/quarkus-test:0.0.11
    # do not add a depends_on:cryostat here, so that we can test that the agent is tolerant of that state
    hostname: quarkus-test-agent
    ports:
      - "9977:9977"
      - "10010:10010"
    environment:
      JAVA_OPTS: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/deployments/app/cryostat-agent.jar"
      QUARKUS_HTTP_PORT: 10010
      ORG_ACME_CRYOSTATSERVICE_ENABLED: "false"
      CRYOSTAT_AGENT_APP_NAME: quarkus-test-agent
      CRYOSTAT_AGENT_WEBSERVER_HOST: quarkus-test-agent
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9977
      CRYOSTAT_AGENT_CALLBACK: http://quarkus-test-agent:9977/
      CRYOSTAT_AGENT_BASEURI: http://cryostat:8181/
      CRYOSTAT_AGENT_SSL_TRUST_ALL: "true"
      CRYOSTAT_AGENT_SSL_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_AUTHORIZATION: Basic dXNlcjpwYXNz # "Basic $(echo -n user:pass | base64)"
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 30000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:10010 || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

