version: "3"
services:
  cryostat:
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512m
    image: ${CRYOSTAT_IMAGE:-quay.io/cryostat/cryostat:latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
    security_opt:
      - label:disable
    hostname: cryostat
    user: "1000"
    expose:
      - "9091"
    ports:
      - "8181:8181"
    labels:
      kompose.service.expose: "cryostat"
      io.cryostat.discovery: "true"
      io.cryostat.jmxHost: "localhost"
      io.cryostat.jmxPort: "0"
      io.cryostat.jmxUrl: "service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi"
    environment:
      QUARKUS_HTTP_HOST: "cryostat"
      CRYOSTAT_HTTP_PROXY_HOST: "auth"
      CRYOSTAT_HTTP_PROXY_PORT: "8080"
      CRYOSTAT_DISCOVERY_DOCKER_ENABLED: "true"
      CRYOSTAT_DISCOVERY_JDP_ENABLED: "true"
      JAVA_OPTS_APPEND: >-
        -XX:+FlightRecorder
        -XX:StartFlightRecording=name=onstart,settings=default,disk=true,maxage=5m
        -Dcom.sun.management.jmxremote.autodiscovery=true
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9091
        -Dcom.sun.management.jmxremote.rmi.port=9091
        -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://cryostat:8181/health/liveness || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
