services:
  cryostat:
    environment:
      - GRAFANA_DASHBOARD_EXT_URL=${GRAFANA_DASHBOARD_EXT_URL:-/grafana/}
      - GRAFANA_DASHBOARD_URL=http://grafana:3000
  grafana:
    image: ${GRAFANA_DASHBOARD_IMAGE:-quay.io/cryostat/cryostat-grafana-dashboard:${CRYOSTAT_VERSION:-latest}}
    hostname: grafana
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256m
    environment:
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=${CRYOSTAT_PROXY_PROTOCOL}://localhost:${CRYOSTAT_PROXY_PORT}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - JFR_DATASOURCE_URL=http://jfr-datasource:8080
    expose:
      - "3000"
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      retries: 3
      interval: 30s
      start_period: 10s
      timeout: 1s
