version: "3"
services:
  cryostat:
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512m
    image: ${CRYOSTAT_IMAGE:-quay.io/cryostat/cryostat:3.0.0-snapshot}
    volumes:
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/run/user/1000/podman/podman.sock:Z
      - jmxtls_cfg:/truststore:U
    security_opt:
      - label:disable
    hostname: cryostat3
    user: "1000"
    labels:
      kompose.service.expose: "cryostat3"
      io.cryostat.discovery: "true"
      io.cryostat.jmxHost: "localhost"
      io.cryostat.jmxPort: "0"
      io.cryostat.jmxUrl: "service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi"
    environment:
      QUARKUS_LOG_LEVEL: TRACE
      QUARKUS_HTTP_HOST: "cryostat"
      QUARKUS_HTTP_PORT: ${CRYOSTAT_HTTP_PORT}
      QUARKUS_HIBERNATE_ORM_LOG_SQL: "true"
      CRYOSTAT_DISCOVERY_JDP_ENABLED: "true"
      CRYOSTAT_DISCOVERY_PODMAN_ENABLED: "true"
      CRYOSTAT_DISCOVERY_DOCKER_ENABLED: "true"
      JAVA_OPTS_APPEND: "-XX:+FlightRecorder -XX:StartFlightRecording=name=onstart,settings=default,disk=true,maxage=5m -XX:StartFlightRecording=name=startup,settings=profile,disk=true,duration=30s -Dcom.sun.management.jmxremote.autodiscovery=true -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9091 -Dcom.sun.management.jmxremote.rmi.port=9091 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://cryostat:${CRYOSTAT_HTTP_PORT}/health/liveness || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

volumes:
  jmxtls_cfg:
    external: true
