version: "3"
services:
  db-viewer:
    depends_on:
      db:
        condition: service_healthy
    image: ${DB_VIEWER_IMAGE:-docker.io/dpage/pgadmin4:7}
    hostname: db-viewer
    ports:
      - "8989:8989"
    expose:
      - "8989"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cryostat.io
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8989
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json:z
      # - ./smoketest/compose/pgpass:/pgpass:z
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8989 || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

volumes:
  pgadmin:
    driver: local

