version: "3"
services:
  cryostat:
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: ${DATABASE_GENERATION:-drop-and-create}
      QUARKUS_DATASOURCE_USERNAME: cryostat3
      QUARKUS_DATASOURCE_PASSWORD: cryostat3
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/cryostat3
  db:
    image: ${CRYOSTAT_DB_IMAGE:-quay.io/cryostat/cryostat-db:latest}
    hostname: db
    expose:
      - "5432"
    environment:
      POSTGRESQL_USER: cryostat3
      POSTGRESQL_PASSWORD: cryostat3
      POSTGRESQL_DATABASE: cryostat3
      PG_ENCRYPT_KEY: REPLACEME
    volumes:
      - postgresql:/var/lib/pgsql/data
    restart: always
    healthcheck:
      test: pg_isready -U cryostat3 -d cryostat3 || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

volumes:
  postgresql:
    driver: local
