version: "3"
services:
  cryostat:
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: ${DATABASE_GENERATION:-none}
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: ${SQL_LOAD_SCRIPT:-no-file}
      QUARKUS_DATASOURCE_USERNAME: cryostat
      QUARKUS_DATASOURCE_PASSWORD: cryostat
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/cryostat
  db:
    image: ${CRYOSTAT_DB_IMAGE:-quay.io/cryostat/cryostat-db:latest}
    hostname: db
    expose:
      - "5432"
    environment:
      POSTGRESQL_USER: cryostat
      POSTGRESQL_PASSWORD: cryostat
      POSTGRESQL_DATABASE: cryostat
      PG_ENCRYPT_KEY: REPLACEME
    volumes:
      - postgresql:/var/lib/pgsql/data
    restart: always
    healthcheck:
      test: pg_isready -U cryostat -d cryostat || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes:
  postgresql:
    driver: local
