services:
  cryostat:
    environment:
      - QUARKUS_REST_CLIENT_REPORTS_URL=http://reports:10001
  reports:
    image: ${CRYOSTAT_REPORTS_IMAGE:-quay.io/cryostat/cryostat-reports:latest}
    hostname: reports
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: ${REPORTS_REPLICAS:-1}
      endpoint_mode: vip
      resources:
        limits:
          cpus: "2"
          memory: 1024m
    expose:
      - "10001"
    labels:
      io.cryostat.discovery: "true"
      io.cryostat.jmxHost: "reports"
      io.cryostat.jmxPort: "11224"
    environment:
      JAVA_OPTS_APPEND: >-
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=11224
        -Dcom.sun.management.jmxremote.rmi.port=11224
        -Djava.rmi.server.hostname=reports
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
      QUARKUS_HTTP_PORT: 10001
      CRYOSTAT_STORAGE_BASE_URI: ${S3_ENDPOINT_ARCHIVES_BUCKET:-http://s3:8333}
    healthcheck:
      test: curl --fail http://localhost:10001/ || exit 1
      retries: 3
      interval: 30s
      start_period: 30s
      timeout: 1s
