services:
  cryostat:
    depends_on:
      s3:
        condition: service_healthy
    environment:
      QUARKUS_S3_ENDPOINT_OVERRIDE: http://s3:8000
      STORAGE_EXT_URL: /storage/
      QUARKUS_S3_PATH_STYLE_ACCESS: "true" # needed since compose setup does not support DNS subdomain resolution
      QUARKUS_S3_AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: accessKey1
      AWS_SECRET_ACCESS_KEY: verySecretKey1
  s3:
    image: ${CLOUDSERVER_IMAGE:-docker.io/zenko/cloudserver:latest}
    hostname: s3
    expose:
      - "8000"
    environment:
      S3BACKEND: mem
      ENDPOINT: s3
      LOG_LEVEL: debug
      REMOTE_MANAGEMENT_DISABLE: 1
      SCALITY_ACCESS_KEY_ID: accessKey1
      SCALITY_SECRET_ACCESS_KEY: verySecretKey1
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - curl
        - --fail
        - http://localhost:8000/_/healthcheck/deep
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
