services:
  cryostat:
    environment:
      QUARKUS_S3_ENDPOINT_OVERRIDE: http://s3:8000
      STORAGE_PRESIGNED_TRANSFERS_ENABLED: false
      STORAGE_EXT_URL: /storage/
      QUARKUS_S3_PATH_STYLE_ACCESS: "true" # needed since compose setup does not support DNS subdomain resolution
      QUARKUS_S3_AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: accessKey1
      AWS_SECRET_ACCESS_KEY: verySecretKey1
  s3:
    # ghcr.io images require authentication to pull, but this is the only up-to-date published source
    image: ${CLOUDSERVER_IMAGE:-ghcr.io/scality/cloudserver:9.2.8}
    hostname: s3
    expose:
      - "8000"
    environment:
      ENDPOINT: s3 # set the expected request hostname to 's3'
      LOG_LEVEL: debug
      REMOTE_MANAGEMENT_DISABLE: 1 # disable integration with proprietary cloud management service
    expose:
      - "8000"
