services:
  cryostat:
    depends_on:
      s3:
        condition: service_healthy
    environment:
      QUARKUS_S3_ENDPOINT_OVERRIDE: http://s3:4566
      STORAGE_PRESIGNED_TRANSFERS_ENABLED: false
      STORAGE_EXT_URL: /storage/
      QUARKUS_S3_PATH_STYLE_ACCESS: "true" # needed since compose setup does not support DNS subdomain resolution
      QUARKUS_S3_AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: unused
      AWS_SECRET_ACCESS_KEY: unused
  s3:
    image: ${LOCALSTACK_IMAGE:-docker.io/localstack/localstack:s3-latest}
    hostname: s3
    expose:
      - "4566"
    environment:
      SERVICES: s3
      START_WEB: 1
    volumes:
      - localstack_cfg:/etc/localstack/init/ready.d:z
    restart: always
    healthcheck:
      test: curl --fail http://localhost:4566 || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

volumes:
  localstack_cfg:
    external: true
