services:
  cryostat:
    depends_on:
      s3:
        condition: service_healthy
    environment:
      QUARKUS_S3_ENDPOINT_OVERRIDE: http://s3:9000
      STORAGE_EXT_URL: /storage/
      QUARKUS_S3_PATH_STYLE_ACCESS: "true" # needed since compose setup does not support DNS subdomain resolution
      QUARKUS_S3_AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: minioroot
      AWS_SECRET_ACCESS_KEY: minioroot
  s3:
    image: ${MINIO_IMAGE:-quay.io/minio/minio:latest}
    hostname: s3
    ports:
      - "9001:9001"
    expose:
      - "9000"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: minioroot
    volumes:
      - minio_data:/data
      - minio_certs:/certs
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - mc
        - ready
        - local
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

volumes:
  minio_data:
    driver: local
  minio_certs:
    driver: local
