version: "3"
services:
  sample-app-1:
    depends_on:
      cryostat:
        condition: service_healthy
    image: ${VERTX_FIB_DEMO_IMAGE:-quay.io/andrewazores/vertx-fib-demo:0.13.1}
    hostname: vertx-fib-demo-1
    environment:
      HTTP_PORT: 8081
      JMX_PORT: 9093
      CRYOSTAT_AGENT_APP_NAME: vertx-fib-demo-1
      CRYOSTAT_AGENT_WEBCLIENT_SSL_TRUST_ALL: "true"
      CRYOSTAT_AGENT_WEBCLIENT_SSL_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_WEBSERVER_HOST: "sample-app-1"
      CRYOSTAT_AGENT_WEBSERVER_PORT: "8910"
      CRYOSTAT_AGENT_CALLBACK: "http://sample-app-1:8910/"
      CRYOSTAT_AGENT_BASEURI: "http://${CRYOSTAT_HTTP_HOST}:8080/"
      CRYOSTAT_AGENT_TRUST_ALL: "true"
      CRYOSTAT_AGENT_AUTHORIZATION: Basic dXNlcjpwYXNz
    ports:
      - "8081:8081"
    expose:
      - "8910"
    labels:
      io.cryostat.discovery: "true"
      io.cryostat.jmxHost: "sample-app-1"
      io.cryostat.jmxPort: "9093"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
  sample-app-2:
    depends_on:
      cryostat:
        condition: service_healthy
    image: ${VERTX_FIB_DEMO_IMAGE:-quay.io/andrewazores/vertx-fib-demo:0.13.1}
    hostname: vertx-fib-demo-2
    environment:
      HTTP_PORT: 8082
      JMX_PORT: 9094
      USE_AUTH: "true"
      CRYOSTAT_AGENT_APP_NAME: "vertx-fib-demo-2"
      CRYOSTAT_AGENT_WEBCLIENT_SSL_TRUST_ALL: "true"
      CRYOSTAT_AGENT_WEBCLIENT_SSL_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_WEBSERVER_HOST: "sample-app-2"
      CRYOSTAT_AGENT_WEBSERVER_PORT: "8911"
      CRYOSTAT_AGENT_CALLBACK: "http://sample-app-2:8911/"
      CRYOSTAT_AGENT_BASEURI: "http://${CRYOSTAT_HTTP_HOST}:8080/"
      CRYOSTAT_AGENT_TRUST_ALL: "true"
      CRYOSTAT_AGENT_AUTHORIZATION: "Basic dXNlcjpwYXNz"
    ports:
      - "8082:8082"
    expose:
      - "8911"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
  sample-app-3:
    depends_on:
      cryostat:
        condition: service_healthy
    image: ${VERTX_FIB_DEMO_IMAGE:-quay.io/andrewazores/vertx-fib-demo:0.13.1}
    hostname: vertx-fib-demo-3
    environment:
      HTTP_PORT: 8083
      JMX_PORT: 9095
      USE_AUTH: "true"
      USE_SSL: "true"
      CRYOSTAT_AGENT_APP_NAME: "vertx-fib-demo-3"
      CRYOSTAT_AGENT_WEBCLIENT_SSL_TRUST_ALL: "true"
      CRYOSTAT_AGENT_WEBCLIENT_SSL_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_WEBSERVER_HOST: "sample-app-3"
      CRYOSTAT_AGENT_WEBSERVER_PORT: "8912"
      CRYOSTAT_AGENT_CALLBACK: "http://sample-app-3:8912/"
      CRYOSTAT_AGENT_BASEURI: "http://${CRYOSTAT_HTTP_HOST}:8080/"
      CRYOSTAT_AGENT_TRUST_ALL: "true"
      CRYOSTAT_AGENT_AUTHORIZATION: "Basic dXNlcjpwYXNz"
    ports:
      - "8083:8083"
    expose:
      - "8912"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
  quarkus-test-agent:
    image: ${QUARKUS_TEST_IMAGE:-quay.io/andrewazores/quarkus-test:latest}
    # do not add a depends_on:cryostat/depends_on:auth here, so that we can test that the agent is tolerant of that state
    hostname: quarkus-test-agent
    ports:
      - "10010:10010"
    expose:
      - "9977"
    environment:
      JAVA_OPTS_APPEND: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/deployments/app/cryostat-agent.jar"
      QUARKUS_HTTP_PORT: 10010
      ORG_ACME_CRYOSTATSERVICE_ENABLED: "false"
      CRYOSTAT_AGENT_APP_NAME: quarkus-test-agent
      CRYOSTAT_AGENT_WEBSERVER_HOST: quarkus-test-agent
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9977
      CRYOSTAT_AGENT_CALLBACK: http://quarkus-test-agent:9977/
      CRYOSTAT_AGENT_BASEURI: http://${CRYOSTAT_HTTP_HOST}:8080/
      CRYOSTAT_AGENT_BASEURI_RANGE: public
      CRYOSTAT_AGENT_SSL_TRUST_ALL: "true"
      CRYOSTAT_AGENT_SSL_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_AUTHORIZATION: Basic dXNlcjpwYXNz # "Basic $(echo -n user:pass | base64)"
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 30000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:10010 || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

