version: "3"
services:
  minecraft-server:
    depends_on:
      cryostat:
        condition: service_healthy
    image: ${MINECRAFT_TEST_IMAGE:-localhost/minecraft-server:latest}
    build:
      context: .
      dockerfile: ./Containerfile.minecraft
    hostname: minecraft
    ports:
      - "7091"
      - "9494"
    environment:
      CRYOSTAT_AGENT_APP_NAME: minecraft
      CRYOSTAT_AGENT_WEBSERVER_HOST: minecraft
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9494
      CRYOSTAT_AGENT_CALLBACK: http://minecraft:9494/
      CRYOSTAT_AGENT_BASEURI: http://${CRYOSTAT_HTTP_HOST}:8080/
      CRYOSTAT_AGENT_BASEURI_RANGE: public
      CRYOSTAT_AGENT_SSL_TRUST_ALL: "true"
      CRYOSTAT_AGENT_SSL_VERIFY_HOSTNAME: "false"
      CRYOSTAT_AGENT_AUTHORIZATION_TYPE: basic
      CRYOSTAT_AGENT_AUTHORIZATION_VALUE: user:pass
      CRYOSTAT_AGENT_API_WRITES_ENABLED: "true"
      CRYOSTAT_AGENT_HARVESTER_TEMPLATE: profiling
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 300000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"
      EULA: "true"
      ENABLE_JMX: "true"
      JMX_HOST: minecraft
      JMX_PORT: "7091"
      JVM_OPTS: -javaagent:/opt/cryostat/agent.jar
