/*
 * Copyright The Cryostat Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.cryostat.graphql;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.function.Predicate;

import io.cryostat.diagnostic.Diagnostics.HeapDump;
import io.cryostat.diagnostic.DiagnosticsHelper;
import io.cryostat.discovery.DiscoveryNode;
import io.cryostat.graphql.ActiveRecordings.MetadataLabels;
import io.cryostat.graphql.RootNode.DiscoveryNodeFilter;
import io.cryostat.graphql.TargetNodes.HeapDumpAggregateInfo;
import io.cryostat.graphql.TargetNodes.HeapDumps;
import io.cryostat.graphql.matchers.LabelSelectorMatcher;
import io.cryostat.recordings.ActiveRecordings.Metadata;
import io.cryostat.recordings.LongRunningRequestGenerator;
import io.cryostat.recordings.LongRunningRequestGenerator.HeapDumpRequest;

import io.smallrye.graphql.api.Nullable;
import io.vertx.mutiny.core.eventbus.EventBus;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import org.eclipse.microprofile.graphql.Description;
import org.eclipse.microprofile.graphql.GraphQLApi;
import org.eclipse.microprofile.graphql.Mutation;
import org.eclipse.microprofile.graphql.NonNull;
import org.eclipse.microprofile.graphql.Query;
import org.eclipse.microprofile.graphql.Source;
import org.jboss.logging.Logger;

@GraphQLApi
public class HeapDumpGraphQL {

    @Inject DiagnosticsHelper diagnosticsHelper;
    @Inject EventBus bus;
    @Inject Logger log;

    @Query("heapDumps")
    @Description("List archived heap dumps")
    public HeapDumps listArchivedHeapDumps(HeapDumpsFilter filter) {
        var r = new TargetNodes.HeapDumps();
        r.data =
                diagnosticsHelper.getHeapDumps(filter == null ? null : filter.sourceTarget).stream()
                        .filter(v -> filter == null ? true : filter.test(v))
                        .toList();
        r.aggregate = HeapDumpAggregateInfo.fromArchived(r.data);
        return r;
    }

    @Transactional
    @Mutation
    @Description(
            "Trigger a heap dump on all Targets under the subtrees of the discovery nodes"
                    + " matching the given filter")
    public List<String> createHeapDump(@NonNull DiscoveryNodeFilter nodes) {
        var list =
                DiscoveryNode.<DiscoveryNode>listAll().stream()
                        .filter(n -> nodes == null ? true : nodes.test(n))
                        .flatMap(
                                node ->
                                        RootNode.recurseChildren(node, n -> n.target != null)
                                                .stream()
                                                .map(n -> n.target))
                        .toList();
        var jobIds = new ArrayList<String>();
        for (var t : list) {
            // Job IDs are generated by the endpoint rather than the
            // helper, need to generate it here
            var jobId = UUID.randomUUID().toString();
            // Delegate to long running framework
            HeapDumpRequest request = new HeapDumpRequest(jobId, t.id);
            bus.publish(LongRunningRequestGenerator.HEAP_DUMP_REQUEST_ADDRESS, request);
            jobIds.add(jobId);
        }
        return jobIds;
    }

    @Transactional
    @Mutation
    @Description(
            "Delete an existing Heap Dump matching the given filter, on all Targets under"
                    + " the subtrees of the discovery nodes matching the given filter")
    public List<HeapDump> deleteHeapDump(
            @NonNull DiscoveryNodeFilter nodes, @Nullable HeapDumpsFilter filter) {
        var list =
                DiscoveryNode.<DiscoveryNode>listAll().stream()
                        .filter(n -> nodes == null ? true : nodes.test(n))
                        .flatMap(
                                node ->
                                        RootNode.recurseChildren(node, n -> n.target != null)
                                                .stream()
                                                .map(n -> n.target))
                        .flatMap(
                                t ->
                                        diagnosticsHelper.getHeapDumps(t).stream()
                                                .filter(h -> filter == null || filter.test(h)))
                        .toList();
        for (var h : list) {
            diagnosticsHelper.deleteHeapDump(h.jvmId(), h.heapDumpId());
        }
        return list;
    }

    @NonNull
    @Description("Delete a heap dump")
    public HeapDump doDelete(@Source HeapDump dump) throws IOException {
        diagnosticsHelper.deleteHeapDump(dump.jvmId(), dump.heapDumpId());
        return dump;
    }

    @NonNull
    @Description("Update the metadata for a heap dump")
    public HeapDump doPutMetadata(@Source HeapDump heapDump, MetadataLabels metadataInput)
            throws IOException {
        diagnosticsHelper.updateHeapDumpMetadata(
                heapDump.jvmId(), heapDump.heapDumpId(), metadataInput.getLabels());

        String downloadUrl =
                diagnosticsHelper.heapDumpDownloadUrl(heapDump.jvmId(), heapDump.heapDumpId());

        return new HeapDump(
                heapDump.jvmId(),
                downloadUrl,
                heapDump.heapDumpId(),
                heapDump.lastModified(),
                heapDump.size(),
                new Metadata(metadataInput.getLabels()));
    }

    public static class HeapDumpsFilter implements Predicate<HeapDump> {
        public @Nullable String name;
        public @Nullable List<String> names;
        public @Nullable String sourceTarget;
        public @Nullable List<String> labels;
        public @Nullable Long sizeBytesGreaterThanEqual;
        public @Nullable Long sizeBytesLessThanEqual;
        public @Nullable Long archivedTimeAfterEqual;
        public @Nullable Long archivedTimeBeforeEqual;

        @Override
        public boolean test(HeapDump t) {
            Predicate<HeapDump> matchesName =
                    n -> name == null || Objects.equals(name, n.heapDumpId());
            Predicate<HeapDump> matchesNames = n -> names == null || names.contains(n.heapDumpId());

            Predicate<HeapDump> matchesSourceTarget =
                    n -> sourceTarget == null || Objects.equals(t.jvmId(), sourceTarget);
            Predicate<HeapDump> matchesSizeGte =
                    n -> sizeBytesGreaterThanEqual == null || sizeBytesGreaterThanEqual >= n.size();
            Predicate<HeapDump> matchesSizeLte =
                    n -> sizeBytesLessThanEqual == null || sizeBytesLessThanEqual <= n.size();
            Predicate<HeapDump> matchesArchivedTimeGte =
                    n ->
                            archivedTimeAfterEqual == null
                                    || archivedTimeAfterEqual >= n.lastModified();
            Predicate<HeapDump> matchesArchivedTimeLte =
                    n ->
                            archivedTimeBeforeEqual == null
                                    || archivedTimeBeforeEqual <= n.lastModified();
            Predicate<HeapDump> matchesLabels =
                    n ->
                            labels == null
                                    || labels.stream()
                                            .allMatch(
                                                    label ->
                                                            LabelSelectorMatcher.parse(label)
                                                                    .test(n.metadata().labels()));

            return List.of(
                            matchesName,
                            matchesNames,
                            matchesSourceTarget,
                            matchesSizeGte,
                            matchesSizeLte,
                            matchesArchivedTimeGte,
                            matchesArchivedTimeLte,
                            matchesLabels)
                    .stream()
                    .reduce(x -> true, Predicate::and)
                    .test(t);
        }
    }
}
