/*
 * Copyright The Cryostat Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.cryostat.graphql;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.function.Predicate;

import io.cryostat.diagnostic.Diagnostics.ThreadDump;
import io.cryostat.diagnostic.DiagnosticsHelper;
import io.cryostat.discovery.DiscoveryNode;
import io.cryostat.graphql.ActiveRecordings.MetadataLabels;
import io.cryostat.graphql.RootNode.DiscoveryNodeFilter;
import io.cryostat.graphql.TargetNodes.ThreadDumpAggregateInfo;
import io.cryostat.graphql.TargetNodes.ThreadDumps;
import io.cryostat.graphql.matchers.LabelSelectorMatcher;
import io.cryostat.recordings.ActiveRecordings.Metadata;
import io.cryostat.recordings.LongRunningRequestGenerator;
import io.cryostat.recordings.LongRunningRequestGenerator.ThreadDumpRequest;

import io.smallrye.graphql.api.Nullable;
import io.vertx.mutiny.core.eventbus.EventBus;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import org.eclipse.microprofile.graphql.Description;
import org.eclipse.microprofile.graphql.GraphQLApi;
import org.eclipse.microprofile.graphql.Mutation;
import org.eclipse.microprofile.graphql.NonNull;
import org.eclipse.microprofile.graphql.Query;
import org.eclipse.microprofile.graphql.Source;
import org.jboss.logging.Logger;

@GraphQLApi
public class ThreadDumpGraphQL {

    @Inject DiagnosticsHelper diagnosticsHelper;
    @Inject EventBus bus;
    @Inject Logger log;

    @Transactional
    @Mutation
    @Description(
            "Trigger a thread dump on all Targets under the subtrees of the discovery nodes"
                    + " matching the given filter")
    public List<String> createThreadDump(@NonNull DiscoveryNodeFilter nodes) {
        var list =
                DiscoveryNode.<DiscoveryNode>listAll().stream()
                        .filter(n -> nodes == null ? true : nodes.test(n))
                        .flatMap(
                                node ->
                                        RootNode.recurseChildren(node, n -> n.target != null)
                                                .stream()
                                                .map(n -> n.target))
                        .toList();
        var jobIds = new ArrayList<String>();
        for (var t : list) {
            // Job IDs are generated by the endpoint rather than the
            // helper, need to generate it here
            var jobId = UUID.randomUUID().toString();
            io.cryostat.diagnostic.ThreadDump.requested(t, jobId, DiagnosticsHelper.DUMP_THREADS)
                    .persist();
            // Delegate to long running framework
            ThreadDumpRequest request =
                    new ThreadDumpRequest(jobId, t.id, DiagnosticsHelper.DUMP_THREADS);
            bus.publish(LongRunningRequestGenerator.THREAD_DUMP_ADDRESS, request);
            jobIds.add(jobId);
        }
        return jobIds;
    }

    @Transactional
    @Mutation
    @Description(
            "Delete an existing Thread Dump matching the given filter, on all Targets under"
                    + " the subtrees of the discovery nodes matching the given filter")
    public List<ThreadDump> deleteThreadDump(
            @NonNull DiscoveryNodeFilter nodes, @Nullable ThreadDumpsFilter filter) {
        var list =
                DiscoveryNode.<DiscoveryNode>listAll().stream()
                        .filter(n -> nodes == null ? true : nodes.test(n))
                        .flatMap(
                                node ->
                                        RootNode.recurseChildren(node, n -> n.target != null)
                                                .stream()
                                                .map(n -> n.target))
                        .flatMap(
                                t ->
                                        diagnosticsHelper.getThreadDumps(t).stream()
                                                .filter(td -> filter == null || filter.test(td)))
                        .toList();
        for (var td : list) {
            diagnosticsHelper.deleteThreadDump(td.jvmId(), td.threadDumpId());
        }
        return list;
    }

    @Query("threadDumps")
    @Description("List archived thread dumps")
    public ThreadDumps listArchivedThreadDumps(ThreadDumpsFilter filter) {
        var r = new TargetNodes.ThreadDumps();
        r.data =
                diagnosticsHelper
                        .getThreadDumps(filter == null ? null : filter.sourceTarget)
                        .stream()
                        .filter(v -> filter == null ? true : filter.test(v))
                        .toList();
        r.aggregate = ThreadDumpAggregateInfo.fromArchived(r.data);
        return r;
    }

    @NonNull
    @Description("Delete a thread dump")
    public ThreadDump doDelete(@Source ThreadDump dump) throws IOException {
        diagnosticsHelper.deleteThreadDump(dump.jvmId(), dump.threadDumpId());
        return dump;
    }

    @NonNull
    @Description("Update the metadata for a thread dump")
    public ThreadDump doPutMetadata(@Source ThreadDump threadDump, MetadataLabels metadataInput)
            throws IOException {
        diagnosticsHelper.updateThreadDumpMetadata(
                threadDump.jvmId(), threadDump.threadDumpId(), metadataInput.getLabels());

        String downloadUrl =
                diagnosticsHelper.threadDumpDownloadUrl(
                        threadDump.jvmId(), threadDump.threadDumpId());

        return new ThreadDump(
                threadDump.jvmId(),
                downloadUrl,
                threadDump.threadDumpId(),
                threadDump.lastModified(),
                threadDump.size(),
                new Metadata(metadataInput.getLabels()));
    }

    public static class ThreadDumpsFilter implements Predicate<ThreadDump> {
        public @Nullable String name;
        public @Nullable List<String> names;
        public @Nullable String sourceTarget;
        public @Nullable List<String> labels;
        public @Nullable Long sizeBytesGreaterThanEqual;
        public @Nullable Long sizeBytesLessThanEqual;
        public @Nullable Long archivedTimeAfterEqual;
        public @Nullable Long archivedTimeBeforeEqual;

        @Override
        public boolean test(ThreadDump t) {
            Predicate<ThreadDump> matchesName =
                    n -> name == null || Objects.equals(name, n.threadDumpId());
            Predicate<ThreadDump> matchesNames =
                    n -> names == null || names.contains(n.threadDumpId());

            Predicate<ThreadDump> matchesSourceTarget =
                    n -> sourceTarget == null || Objects.equals(t.jvmId(), sourceTarget);
            Predicate<ThreadDump> matchesSizeGte =
                    n -> sizeBytesGreaterThanEqual == null || sizeBytesGreaterThanEqual >= n.size();
            Predicate<ThreadDump> matchesSizeLte =
                    n -> sizeBytesLessThanEqual == null || sizeBytesLessThanEqual <= n.size();
            Predicate<ThreadDump> matchesArchivedTimeGte =
                    n ->
                            archivedTimeAfterEqual == null
                                    || archivedTimeAfterEqual >= n.lastModified();
            Predicate<ThreadDump> matchesArchivedTimeLte =
                    n ->
                            archivedTimeBeforeEqual == null
                                    || archivedTimeBeforeEqual <= n.lastModified();
            Predicate<ThreadDump> matchesLabels =
                    n ->
                            labels == null
                                    || labels.stream()
                                            .allMatch(
                                                    label ->
                                                            LabelSelectorMatcher.parse(label)
                                                                    .test(n.metadata().labels()));

            return List.of(
                            matchesName,
                            matchesNames,
                            matchesSourceTarget,
                            matchesSizeGte,
                            matchesSizeLte,
                            matchesArchivedTimeGte,
                            matchesArchivedTimeLte,
                            matchesLabels)
                    .stream()
                    .reduce(x -> true, Predicate::and)
                    .test(t);
        }
    }
}
